#LISTS OF UNITS /////////////////////////////////////////////////
terran_units = [
    'Battlecruiser',
    'Dropship',
    'Firebat',
    'Ghost',
    'Goliath',
    'Marine',
    'Medic',
    'Science Vessel',
    'SCV',
    'Siege Tank (Siege Mode)',
    'Siege Tank (Tank Mode)',
    'Spider Mine',
    'Valkyrie',
    'Vulture',
    'Wraith'
]
zerg_units = [
    'Broodling',
    'Defiler',
    'Devourer',
    'Drone',
    'Guardian',
    'Hydralisk',
    'Infested Terran',
    'Lurker',
    'Mutalisk',
    'Overlord',
    'Queen',
    'Scourge',
    'Ultralisk',
    'Zergling'
]
protoss_units = [
    'Arbiter',
    'Archon',
    'Carrier',
    'Corsair',
    'Dark Archon',
    'Dark Templar',
    'Dragoon',
    'High Templar',
    'Observer',
    'Probe',
    'Reaver',
    'Scout',
    'Shuttle',
    'Zealot'
]
other_units = [
    'Bengalaas (Jungle)',
    'Data Disc',
    'Flag',
    'Kakaru (Twilight)',
    'Khalis Crystal',
    'Khaydarin Crystal',
    'Psi Emitter',
    'Ragnasaur (Ash World)',
    'Rhynadon (Badlands)',
    'Scantid (Desert)',
    'Uraj Crystal',
    'Ursadon (Ice World)',
    'Young Chrysalis'
]
DC_units = [
    'Cantina',
    'Cave',
    'Data Disc',
    'Flag',
    'Overmind Cocoon'
]
wall_units = [
    'Data Disc',
    'Flag',
    'Khalis Crystal',
    'Khaydarin Crystal',
    'Psi Emitter',
    'Uraj Crystal',
    'Young Chrysalis',
    'Terran Machine Shop',
    'Vespene Orb (Protoss Type 1)'
]
#////////////////////////////////////////////////////////////////

#LISTS OF SPRITES ///////////////////////////////////////////////
spell_sprites = [
    'Burrowing Dust',
    'Defensive Matrix Hit (Small)',
    'Defensive Matrix Hit (Medium)',
    'Defensive Matrix Hit (Large)',
    'Ensnare Cloud',
    'Hallucination Death1',
    'Maelstrom Hit',
    'Mind Control Hit (Small)',
    'Mind Control Hit (Medium)',
    'Mind Control Hit (Large)',
    'Optical Flare Hit (Small)',
    'Optical Flare Hit (Medium)',
    'Optical Flare Hit (Large)',
    'Plague Cloud',
    'Psionic Storm',
    'Recall Field',
    'Stasis Field Hit',
    'Yamato Gun Hit'
]

attack_sprites = [
    'Acid Spore',
    'Acid Spore Hit',
    'Archon Beam',
    'Arclite Shock Cannon Hit',
    'Corrosive Acid Hit',
    'FlameThrower',
    'Glave Wurm Hit [!]',
    'Grenade Shot Smoke',
    'Halo Rockets Trail',
    'Needle Spines',
    'Neutron Flare [!]',
    'Phase Disruptor',
    'Phase Disruptor Hit',
    'Psionic Shockwave Hit',
    'Scarab Hit',
    'Sunken Colony Tentacle',
    'Venom Hit (Unused)'
]

unit_sprites = [
    'Dark Archon Death',
    'Explosion1 (Small)',
    'Explosion1 (Medium)',
    'Explosion2 (Small)',
    'Explosion2 (Medium)',
    'Nuclear Missile Death',
    'Spider Mine Death',
    'Zerg Air Death Explosion (Large)',
    'Zerg Air Death Explosion (Small)'
]

other_sprites = [
    'Building Landing Dust Type1',
    'Building Landing Dust Type2',
    'Building Landing Dust Type3',
    'Building Landing Dust Type4',
    'Building Landing Dust Type5',
    'Vespene Geyser Smoke1',
    'Vespene Geyser Smoke2',
    'Vespene Geyser Smoke3',
    'Vespene Geyser Smoke4',
    'Vespene Geyser Smoke5'
]

#IMAGE INDICES OF SPRITES /////////////////////////////////////
image_indices = {
    'Scourge Explosion': 4,
    'Infested Terran Explosion': 10,
    'Needle Spines': 35,
    'Zerg Air Death Explosion (Large)': 58,
    'Zerg Air Death Explosion (Small)': 59,
    'Explosion1 (Small)': 213,
    'Explosion1 (Medium)': 214,
    'Explosion2 (Small)': 332,
    'Explosion2 (Medium)': 333,
    'Stasis Field Hit': 364,
    'Defensive Matrix Hit (Small)': 377,
    'Defensive Matrix Hit (Medium)': 378,
    'Defensive Matrix Hit (Large)': 379,
    'Ensnare Cloud': 383,
    'Plague Cloud': 387,
    'Recall Field': 391,
    'FlameThrower': 421,
    'Burrowing Dust': 423,
    'Phase Disruptor Hit': 427,
    'Nuclear Missile Death': 428,
    'Spider Mine Death': 429,
    'Vespene Geyser Smoke1': 430,
    'Vespene Geyser Smoke2': 431,
    'Vespene Geyser Smoke3': 432,
    'Vespene Geyser Smoke4': 433,
    'Vespene Geyser Smoke5': 434,
    'Grenade Shot Smoke': 441,
    'Scarab/Anti-Matter Missile Overlay': 443,
    'Scarab Hit': 444,
    'Burst Lasers Hit': 447,
    'Building Landing Dust Type1': 494,
    'Building Landing Dust Type2': 495,
    'Building Landing Dust Type3': 496,
    'Building Landing Dust Type4': 497,
    'Building Landing Dust Type5': 498,
    'Sunken Colony Tentacle': 506,
    'Acid Spore': 509,
    'Acid Spore Hit': 510,
    'Glave Wurm Hit [!]': 512,
    'Consume': 517,
    'Guardian Attack Overlay': 518,
    'Dual Photon Blasters Hit': 519,
    'Phase Disruptor': 523,
    'STA/STS Photon Cannon Overlay': 524,
    'Psionic Storm': 525,
    'Arclite Shock Cannon Hit': 533,
    'Siege Tank(Siege) Turret Attack': 537,
    'Yamato Gun Hit': 544,
    'Hallucination Hit': 546,
    'Psionic Shockwave Hit': 548,
    'Archon Beam': 549,
    'EMP Shockwave Hit (Part1)': 555,
    'EMP Shockwave Hit (Part2)': 556,
    'Hallucination Death1': 557,
    'Dark Archon Death': 928,
    'Halo Rockets Trail': 960,
    'Subterranean Spines': 961,
    'Corrosive Acid Hit': 963,
    'Neutron Flare': 964,
    'Mind Control Hit (Small)': 973,
    'Mind Control Hit (Medium)': 974,
    'Mind Control Hit (Large)': 975,
    'Optical Flare Hit (Small)': 976,
    'Optical Flare Hit (Medium)': 977,
    'Optical Flare Hit (Large)': 978,
    'Feedback (Small)': 979,
    'Feedback (Medium)': 980,
    'Feedback Hit (Large)': 981,
    'Maelstrom Hit': 998,
}
#//////////////////////////////////////////////////////////////